#!/bin/bash
# Simple script that launces the default browser after converting RST file to
# HTML and saving it in the tmp directory.

tmpfile=/tmp/`date +%Y_%m_%d_%H_%M`.html
rst2html.py $1 > $tmpfile
gnome-open $tmpfile
